### ISSUE TITLE
esp-hal-smartled 0.17 doesn't build with esp-hal 1.1

### ISSUE THREAD

**Issue by sukhmel** [esp-rs/esp-hal-community#66]
This is in part an error in managing dependencies, since I get this issue while trying to access smartled from Ariel OS app template. 

What Ariel OS re-exports as esp-hal 1.0 seems to have an API of esp-hal 1.1, see https://docs.rs/esp-hal/1.1.0/esp_hal/rmt/ here channels no longer accept pin in constructor. I'm not sure how to manage this issue, since this is an API change in minor version update. 

 The error is as follows:

```
error[E0061]: this method takes 1 argument but 2 arguments were supplied
    --> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-hal-smartled-0.17.0/src/lib.rs:217:31
     |
 208 |     pub fn new_with_color<C, O>(
     |                              - found this type parameter
...
 217 |         let channel = channel.configure_tx(pin, led_config()).unwrap();
     |                               ^^^^^^^^^^^^      ------------ unexpected argument #2 of type `TxChannelConfig`
     |
note: expected `&TxChannelConfig`, found type parameter `O`
    --> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-hal-smartled-0.17.0/src/lib.rs:217:44
     |
 217 |         let channel = channel.configure_tx(pin, led_config()).unwrap();
     |                                            ^^^
     = note:   expected reference `&TxChannelConfig`
             found type parameter `O`
note: method defined here
    --> /home/user/.cargo/git/checkouts/esp-hal-56b75427f497a0b9/531c629/esp-hal/src/rmt.rs:1330:8
     |
1330 |     fn configure_tx(self, config: &TxChannelConfig) -> Result<Channel<'ch, Dm, Tx>, ConfigError>
     |        ^^^^^^^^^^^^
help: remove the extra argument
     |
 217 -         let channel = channel.configure_tx(pin, led_config()).unwrap();
 217 +         let channel = channel.configure_tx(/* &TxChannelConfig */).unwrap();
     |

error[E0277]: `?` couldn't convert the error to `LedAdapterError`
   --> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-hal-smartled-0.17.0/src/lib.rs:262:48
    |
262 |         match channel.transmit(self.rmt_buffer)?.wait() {
    |                       -------------------------^ the trait `From<(esp_hal::rmt::Error, esp_hal::rmt::Channel<'_, Blocking, esp_hal::rmt::Tx>)>` is not implemented for `LedAdapterError`
    |                       |
    |                       this can't be annotated with `?` because it has type `Result<_, (esp_hal::rmt::Error, esp_hal::rmt::Channel<'_, Blocking, esp_hal::rmt::Tx>)>`
    |
note: `LedAdapterError` needs to implement `From<(esp_hal::rmt::Error, esp_hal::rmt::Channel<'_, Blocking, esp_hal::rmt::Tx>)>`
   --> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-hal-smartled-0.17.0/src/lib.rs:68:1
    |
 68 | pub enum LedAdapterError {
    | ^^^^^^^^^^^^^^^^^^^^^^^^
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
help: the trait `From<(esp_hal::rmt::Error, esp_hal::rmt::Channel<'_, Blocking, esp_hal::rmt::Tx>)>` is not implemented for `LedAdapterError`
      but trait `From<esp_hal::rmt::Error>` is implemented for it
   --> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-hal-smartled-0.17.0/src/lib.rs:75:1
    |
 75 | impl From<RmtError> for LedAdapterError {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: for that trait implementation, expected `esp_hal::rmt::Error`, found `(esp_hal::rmt::Error, esp_hal::rmt::Channel<'_, Blocking, esp_hal::rmt::Tx>)`

error[E0061]: this method takes 1 argument but 2 arguments were supplied
    --> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-hal-smartled-0.17.0/src/lib.rs:335:31
     |
 326 |     pub fn new_with_color<C, O>(
     |                              - found this type parameter
...
 335 |         let channel = channel.configure_tx(pin, led_config()).unwrap();
     |                               ^^^^^^^^^^^^      ------------ unexpected argument #2 of type `TxChannelConfig`
     |
note: expected `&TxChannelConfig`, found type parameter `O`
    --> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-hal-smartled-0.17.0/src/lib.rs:335:44
     |
 335 |         let channel = channel.configure_tx(pin, led_config()).unwrap();
     |                                            ^^^
     = note:   expected reference `&TxChannelConfig`
             found type parameter `O`
note: method defined here
    --> /home/user/.cargo/git/checkouts/esp-hal-56b75427f497a0b9/531c629/esp-hal/src/rmt.rs:1330:8
     |
1330 |     fn configure_tx(self, config: &TxChannelConfig) -> Result<Channel<'ch, Dm, Tx>, ConfigError>
     |        ^^^^^^^^^^^^
help: remove the extra argument
     |
 335 -         let channel = channel.configure_tx(pin, led_config()).unwrap();
 335 +         let channel = channel.configure_tx(/* &TxChannelConfig */).unwrap();
     |

Some errors have detailed explanations: E0061, E0277.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `esp-hal-smartled` (lib) due to 3 previous errors
```

Cargo tree parts:

```
$ cargo tree -i esp-hal-smartled
esp-hal-smartled v0.17.0
└── esp32c3-playground v0.1.0 (/home/user/Projects/esp32c3-playground)

$  cargo tree -i esp-hal
esp-hal v1.0.0 (https://github.com/ariel-os/esp-hal?rev=531c629afdd80ea464682ce7f4db8baed97967a6#531c629a)
├── esp-hal-smartled v0.17.0
│   └── esp32c3-playground v0.1.0 (/home/user/Projects/esp32c3-playground)
└── esp32c3-playground v0.1.0 (/home/user/Projects/esp32c3-playground)
```

This diff seems to fix an issue, but I'm unsure if it completely correct and what to do with it, maybe it can be incorporated along with version bump and a dependency version bump?:
 
```diff
diff -ru /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-hal-smartled-0.17.0/src/lib.rs /home/user/Projects/esp32c3-playground/patches/esp-hal-smartled/src/lib.rs
--- /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-hal-smartled-0.17.0/src/lib.rs       2006-07-24 03:21:28.000000000 +0200
+++ /home/user/Projects/esp32c3-playground/patches/esp-hal-smartled/src/lib.rs       2026-05-26 14:15:19.460933331 +0200
@@ -214,7 +214,7 @@
         O: PeripheralOutput<'ch>,
         C: TxChannelCreator<'ch, Blocking>,
     {
-        let channel = channel.configure_tx(pin, led_config()).unwrap();
+        let channel = channel.configure_tx(&led_config()).unwrap().with_pin(pin);
 
         // Assume the RMT peripheral is set up to use the APB clock
         let src_clock = Clocks::get().apb_clock.as_mhz();
@@ -259,14 +259,21 @@
 
         // Perform the actual RMT operation.
         let channel = self.channel.take().unwrap();
-        match channel.transmit(self.rmt_buffer)?.wait() {
+        let transaction = match channel.transmit(self.rmt_buffer) {
+            Ok(tx) => tx,
+            Err((e, chan)) => {
+                self.channel = Some(chan);
+                return Err(LedAdapterError::from(e));
+            }
+        };
+        match transaction.wait() {
             Ok(chan) => {
                 self.channel = Some(chan);
                 Ok(())
             }
             Err((e, chan)) => {
                 self.channel = Some(chan);
-                Err(LedAdapterError::TransmissionError(e))
+                Err(LedAdapterError::from(e))
             }
         }
     }
@@ -332,7 +339,7 @@
         O: PeripheralOutput<'ch>,
         C: TxChannelCreator<'ch, Async>,
     {
-        let channel = channel.configure_tx(pin, led_config()).unwrap();
+        let channel = channel.configure_tx(&led_config()).unwrap().with_pin(pin);
 
         // Assume the RMT peripheral is set up to use the APB clock
         let src_clock = Clocks::get().apb_clock.as_mhz();
```

**Comment by MabezDev** [comment]
We make breaking changes to _unstable_ drivers (see: https://github.com/esp-rs/esp-hal/tree/main/esp-hal#peripheral-support), so yes there will be breakages per minor/major release. If you wish to not auto update, which we recommend, then use cargo's `~` operator to define esp-hal. I.e instead of `"1.0"` its "1.0~" which will prevent auto bump of the minor version.

The real fix here is to update esp-hal-smartled: https://github.com/esp-rs/esp-hal-community/pull/62.

**Comment by sukhmel** [comment]
Makes sense, I forgot it's unstable. Yes, the updated version should fix this, I will try to build with that branchz thanks for pointing out. I guess, the issue can be closed now
